ISSUE-229: Remove check consistency code, test and related docs
iotaledger/iota.lib.java pull request #234
Opened 2020-10-02 07:20 UTC by ezienecker

# Description of change

Preparation for https://github.com/iotaledger/iota-java/issues/229

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which remove functionality)
- Documentation Fix

## How the change has been tested

run mvn clean install

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests using ginkgo that prove my fix is effective or that my feature works -> not needed
- [ ] New and existing unit tests pass locally with my changes -> not needed

2020-10-05 17:36 UTC, kwek20 requested changes
Can you also remove `CheckConsistencyResponse.java`? Thanks for the fix!

2020-10-05 17:36 UTC, kwek20 commented on docs/iota-java/isPromotable.md
>  | [ArgumentException](https://github.com/iotaledger/iota-java/blob/master/jota/src/main/java/org/iota/jota/error/ArgumentException.java) | when we can't get the consistency of this transaction |
Can you remove the exception here?

2020-10-05 17:36 UTC, kwek20 commented on jota/src/main/java/org/iota/jota/IotaAPI.java
>      public boolean isPromotable(Transaction tail) throws ArgumentException {
and this method doesnt throw it anymore

2020-10-05 17:36 UTC, kwek20 commented on jota/src/main/java/org/iota/jota/IotaAPI.java
>       * @throws ArgumentException when we can't get the consistency of this transaction
This method still throws it, but replace explanation to "When we cant find the transaction"

2020-10-11 17:10 UTC, kwek20 commented
@ezienecker

2020-10-11 17:19 UTC, ezienecker commented
@kwek20 done

2020-10-11 17:21 UTC, merged

2020-10-11 17:21 UTC, kwek20 commented
Legend!