[wip] First Draft for module reorg and Travis fixes.
iotaledger/iota.lib.java pull request #33
Opened 2017-08-20 14:10 UTC by jpkrohling

2017-08-20 14:12 UTC, jpkrohling commented
@pinpong , this is just an initial draft for the three next steps from #32 . I'd appreciate your review once you have some time. No actual code should have been changed, only reorganizing the modules. Once it's reviewed and merge, I'll send my PR for the `Kerl.java` and `Converter`

2017-09-09 19:40 UTC, adrianziser approved these changes

2017-09-09 19:51 UTC, adrianziser requested changes
Oli has requested alon to review this but i dont think he will find the time atm. i just had a look and it looks good for me + i welcome the changes. Sorry that i merged other pr before yours, could you please resolve the conflicts and resubmit your pr that we can finally accept & merge it?

2017-09-21 11:06 UTC, jpkrohling commented
Sorry for the delay, I've been a bit busy for the last couple of weeks but I'll rebase and update this PR soon.

2017-10-25 08:27 UTC, jpkrohling commented
This PR has been rebased and updated to fix the merge conflicts.

2017-10-27 08:16 UTC, th0br0 commented on pom.xml
> +                <version>1.57</version>
Could you bump to `1.58`? There were a number of Keccak(Kerl) performance improvements.

2017-10-27 08:16 UTC, th0br0 commented
Looks sane to me! Could you just bump the bouncycastle version?

2017-10-27 12:45 UTC, jpkrohling commented
Version bumped

2017-10-27 15:57 UTC, merged